import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import googleAuthRouter from "./google-auth";
import servicesRouter from "./services";
import countriesRouter from "./countries";
import numbersRouter from "./numbers";
import walletRouter from "./wallet";
import dashboardRouter from "./dashboard";
import adminRouter from "./admin";
import adminSupportRouter from "./admin-support";
import adminAuthRouter from "./admin-auth";
import adminNotificationsRouter from "./admin-notifications";
import adminEmailsRouter from "./admin-emails";
import adminPaymentRoutingRouter from "./admin-payment-routing";
import configRouter from "./config";
import currenciesRouter from "./currencies";
import footerRouter from "./footer";
import supportRouter from "./support";
import notificationsRouter from "./notifications";
import bannersRouter from "./banners";
import otpRouter from "./otp";
import forgotPasswordRouter from "./forgot-password";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(configRouter);
router.use(authRouter);
router.use(googleAuthRouter);
router.use(servicesRouter);
router.use(countriesRouter);
router.use(numbersRouter);
router.use(walletRouter);
router.use(dashboardRouter);
router.use(currenciesRouter);
router.use(adminAuthRouter);
router.use(footerRouter);
router.use(supportRouter);
router.use(notificationsRouter);
router.use(bannersRouter);
router.use(otpRouter);
router.use(forgotPasswordRouter);
router.use(adminRouter);
router.use(adminSupportRouter);
router.use(adminNotificationsRouter);
router.use(adminEmailsRouter);
router.use(adminPaymentRoutingRouter);

export default router;
