kind = "web"
previewPath = "/"
title = "Simix"
version = "1.0.0"
id = "artifacts/simix"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23017

[services.development]
run = "pnpm --filter @workspace/simix run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/simix", "run", "build" ]
publicDir = "artifacts/simix/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23017"
BASE_PATH = "/"
