// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bienvenue/Bienvenue.tsx": () => import("../components/mockups/bienvenue/Bienvenue.tsx"),
  "./components/mockups/landing/HeroImpact.tsx": () => import("../components/mockups/landing/HeroImpact.tsx"),
  "./components/mockups/landing/MinimalPremium.tsx": () => import("../components/mockups/landing/MinimalPremium.tsx"),
  "./components/mockups/landing/SocialProof.tsx": () => import("../components/mockups/landing/SocialProof.tsx")
};
